name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        IMAGE_TAG=latest
        docker build -t ${{ secrets.DOCKER_USERNAME }}/test-app:$IMAGE_TAG .
        docker push ${{ secrets.DOCKER_USERNAME }}/test-app:$IMAGE_TAG

    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "Pulling latest image..."
          docker pull ${{ secrets.DOCKER_USERNAME }}/test-app:latest
          
          echo "Updating Kubernetes deployment..."
          kubectl set image deployment/test-app test-app=${{ secrets.DOCKER_USERNAME }}/test-app:latest --record
          
          echo "Restarting pod..."
          kubectl rollout restart deployment test-app

    - name: Verify Deployment
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "Checking pod status..."
          kubectl get pods -o wide
